### ISSUE TITLE
js error on resize

### ISSUE THREAD

**Issue by senderle** [senderle/c18topics#7]
On resize now, a JS error reports:

```
Uncaught TypeError: svg.attr is not a function
    at resize (plot.js:36)
    at d3.v3.min.js:1
```

Seems to have something to do with the way the callback is receiving the svg object. It might be necessary to get the `svg` object into the `resize` function's closure.

**Comment by maecapozzi** [comment]
I think I have resolved this issue with [this PR](https://github.com/senderle/c18topics/pull/8).
